# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjT838MhxdF_JB38L16S6tO89KabENxu

#Installation of Numpy
"""

pip install numpy

import numpy
print(numpy.__version__)

import numpy as np

"""#Creation of Numpy Elements"""

a = np.array
print(a)

a = np.array([1,2,3])
print(a)

"""#Type functions in Numpy"""

a = np.array([1,2,3])
print(a)
#Returns type of an array
print(type(a))
#Returns data types of elements inside the array
print(a.dtype)
#Returns dimensions of numpy array
print(a.ndim)

a = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

a = np.array([1,2,3], complex)
print(a)

"""#Sizes and shapes of Numpy"""

a = np.array([[1,2,3,4,5,6]])
print(a.size) # no.of elements
print(a.shape) #(rows,columns)

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)

a = np.array([[1,2,],[3,4],[5,6]])
print('Original array')
print(a)

a = a.reshape(2,3)
print('Reshaped array')
print(a)

"""#Accessing of elements in Numpy"""

a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[0,1])
print(a[2,1])
print(a[1,1])

"""#Functions in Numpy"""

a = np.array([1,2,3,50,4,45,4])
print(a)
print(a.max())
print(a.min())
print(a.sum())

"""#Identity of Numpy"""

np.identity(4)

b = np.zeros((3,4))
print(b)

b = np.ones((3,2))
print(b)

a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min(axis=1))
print(a.min(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=0))

# randn --> generates random number between (-1,0,1)

a = np.random.randn(3,4)
print(a)

# Arithmetic operation

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[10,5,15]])

print("Addition of a and b:\n ", a+b)
print('*********************************')
print("Subtraction of a and b:\n ", a-b)
print('*********************************')
print("Product of a and b:\n", a*b)
print('*********************************')
print("division of a and b: \n", a/b)

#Ranging function ---> range()

for i in range(12):
    print(i, end=' ')

# Ranging function in numpy --> arange()

print(np.arange(12))

print(np.arange(12).reshape(3,4))

arr = np.arange(12).reshape(2,2,3) # --> 2*3, 2*3 (generates 2 matrices)
print(arr)
print('*********************************')
print(arr[0])
print('*********************************')
print(arr[1])
print('*********************************')
print(arr[0][1])
print('*********************************')
print(arr[0][1][2])

print(np.arange(12))
print(np.arange(12)[0:7])
print(np.arange(12)[0:7][1])

# Numpy Broadcasting

a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a+b
print(c)

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([2,4,6,8])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a+b)
print('*********************************')
print(a-b)
print('*********************************')
print(a*b)

arr1 = np.arange(15).reshape(5,3)
print(arr1)
print('*********************************')
arr2 = np.arange(5).reshape(5,1)
print(arr2)
print('*********************************')
print(arr1 + arr2)

print(np.array(['apple','banana','cherry']))
print('*********************************')
print(np.array([['welcome'],['hi']]))

print(np.char.add(['welcome'],['hi']))

arr = np.array(["A","B"])
result = np.char.multiply(arr,3)
print(result)

# Round function ---> around()

arr = np.array([12.2, 90.12, 12.54789, 52.85])
print(arr)
print("Rounding function: ", np.around(arr))
print('*********************************')
print("With decimal:",np.around(arr, 2) )

arr = np.array([12.2, 90.12, 12.54, 52.85])
print("Floor: ", np.floor(arr))
print("Ceil: ", np.ceil(arr))

# Mean, Median, Average

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
print(np.median(a))
print('*********************************')
print(np.median(a,0)) #--> axis = rows
print('*********************************')
print(np.median(a,1)) # --> axis = Columns
print('*********************************')
print(np.mean(a))
print('*********************************')
print(np.average(a))

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
at = a.T # Transpose --> rows changes to columns, columns changes to rows
print(at)

a = np.array([[100,200],[30,40]])
b = np.array([[10,20],[50,60]])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a*b) # --> Multiplication
print('*********************************')
print(np.dot(a,b)) # --> Dot product