# -*- coding: utf-8 -*-
"""Date and Time Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zq065q3S0rmf_1HW3Y0pEJQNIsatda54

date --> year, month and date as attributes

time --> 24 hours, 60 minutes, 60 seconds and microsecond, tzinfo

datetime --> year, month, day, hour, minute, second, microsecond and tzinfo

timedelta --> difference between two dates, time or datetime instances

tzinfo --> it provides time zone information

TimeZone --> region of the earth that has uniform standard time for UTC(Coordinated Universal time)
"""

import time

print(time.localtime(time.time()))

"""Year = 4 digit

Month = 1 to 12

Day = 1 to 31

Hour = 0 to 23

Minute = 0 to 59

Second = 0 to 60

tm_wday = Day of the week(0 to 6)

(Monday - 0, Tuesday - 1, Wednesday - 2, Thursday - 3, Friday - 4, Saturday - 5, Sunday - 6)

tm_yday --> Day of the year = 1 to 365 / 366

tm_isdst --> Daylight Savings = -1,0,1
"""

print(time.asctime(time.localtime(time.time())))

#Seconds
for i in range(0, 10):
    print(i)
    time.sleep(5)

from datetime import datetime

print(datetime.now())

from datetime import datetime

current_datetime = datetime.now()

print(current_datetime.year)
year = current_datetime.year
month = current_datetime.month
day = current_datetime.day
hour = current_datetime.hour
minute = current_datetime.minute
second = current_datetime.second
microsecond = current_datetime.microsecond


print(f"Year: {year}")
print(f"Month: {month}")
print(f"Day: {day}")
print(f"Hour: {hour}")
print(f"Minute: {minute}")
print(f"Second: {second}")
print(f"Microsecond: {microsecond}")

import datetime
date_obj = datetime.date.today()
print(date_obj)

import datetime
print(datetime.datetime(2023,12,4,8,34,50))

from datetime import date
timestamp = date.fromtimestamp(123556788)
print("Date:",timestamp)

from datetime import datetime

current_time = datetime.now()
ts = current_time.timestamp()
print(ts)

# Calendar Module

import calendar

a = calendar.month(2024, 4)
print(a)

#The prcal() method is used to print the calendar for an entire year.
a = calendar.prcal(2024)
print(a)

from calendar import *
y = int(input("Enter the Year: "))
print(isleap(y))